export enum RabbitMQ {
  DestinoSufragioQueue = 'destino-sufragio',
}

export enum DestinoSufragioMSG {
  CREATE = 'CREATE_DESTINO_SUFRAGIO',
  DELETE = 'DELETE_DESTINO_SUFRAGIO',
  FIND_ALL = 'FIND_DESTINOS_SUFRAGIO',
  FIND_ONE = 'FIND_DESTINO_SUFRAGIO',
  FIND_BY_PERSONA_NATURAL = 'FIND_BY_PERSONA_NATURAL',
  FIND_BY_DUI = 'FIND_BY_DUI',
  CREATE_VOTE = 'CREATE_VOTE',
  VERIFY_STATUS_VOTE = 'VERIFY_STATUS_VOTE',
  VALIDATE_VOTE = 'VALIDATE_VOTE',
  CAST_VOTE = 'CAST_VOTE'
}

export enum SufragiosMSG {
  FIND_ALL = 'FIND_ALL_SUFRAGIOS',
}
